export const INITIAL_LEAVE_BALANCES = [
  {
    id: "cl",
    code: "CL",
    name: "Casual Leave",
    allocated: 12,
    used: 4,
    pending: 1,
    available: 7,
    color: "#00DC46",
    description: "For personal emergencies, family events, or unplanned casual needs.",
  },
  {
    id: "sl",
    code: "SL",
    name: "Sick Leave",
    allocated: 10,
    used: 2,
    pending: 0,
    available: 8,
    color: "#FF6A3D",
    description: "Medical absences, recuperation, or outpatient procedures.",
  },
  {
    id: "el",
    code: "EL",
    name: "Earned Leave",
    allocated: 18,
    used: 5,
    pending: 2,
    available: 11,
    color: "#7C3AED",
    description: "Privilege annual vacation leave accrued throughout the tenure.",
  },
  {
    id: "co",
    code: "CO",
    name: "Compensatory Off",
    allocated: 4,
    used: 1,
    pending: 0,
    available: 3,
    color: "#0284C7",
    description: "Credit days earned by working on weekends or designated holidays.",
  },
  {
    id: "ol",
    code: "OL",
    name: "Optional / Holiday",
    allocated: 3,
    used: 1,
    pending: 0,
    available: 2,
    color: "#EAB308",
    description: "Restricted religious or cultural holidays chosen from company list.",
  },
];

export const INITIAL_MY_LEAVES = [
  {
    id: "LV-2026-001",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Casual Leave",
    leaveCode: "CL",
    fromDate: "2026-09-24",
    toDate: "2026-09-25",
    days: 2,
    halfDay: false,
    reason: "Attending sister's engagement ceremony in hometown.",
    appliedDate: "2026-09-20",
    status: "Pending",
    approver: "Vikram Malhotra",
    remarks: "Under manager review",
    attachment: "invitation_card.pdf",
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-09-20 10:15 AM", status: "completed" },
      { step: "Manager Approval", by: "Vikram Malhotra", date: "Pending", status: "current" },
      { step: "HR Acknowledgment", by: "Priya Nair", date: "Queued", status: "upcoming" },
    ],
  },
  {
    id: "LV-2026-002",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Sick Leave",
    leaveCode: "SL",
    fromDate: "2026-09-10",
    toDate: "2026-09-11",
    days: 2,
    halfDay: false,
    reason: "Viral flu and high temperature. Advised 48h rest by physician.",
    appliedDate: "2026-09-10",
    status: "Approved",
    approver: "Vikram Malhotra",
    remarks: "Approved. Take care and take sufficient rest.",
    attachment: "medical_prescription.pdf",
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-09-10 08:30 AM", status: "completed" },
      { step: "Manager Approval", by: "Vikram Malhotra", date: "2026-09-10 09:15 AM", status: "completed" },
      { step: "HR Acknowledged", by: "Priya Nair", date: "2026-09-10 10:00 AM", status: "completed" },
    ],
  },
  {
    id: "LV-2026-003",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Earned Leave",
    leaveCode: "EL",
    fromDate: "2026-08-15",
    toDate: "2026-08-19",
    days: 5,
    halfDay: false,
    reason: "Annual family trip to Ladakh.",
    appliedDate: "2026-07-25",
    status: "Approved",
    approver: "Vikram Malhotra",
    remarks: "Approved. Sprint tasks delegated to Rohan.",
    attachment: null,
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-07-25 11:20 AM", status: "completed" },
      { step: "Manager Approval", by: "Vikram Malhotra", date: "2026-07-26 02:45 PM", status: "completed" },
    ],
  },
  {
    id: "LV-2026-004",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Casual Leave",
    leaveCode: "CL",
    fromDate: "2026-07-02",
    toDate: "2026-07-02",
    days: 0.5,
    halfDay: true,
    halfDaySession: "Second Half",
    reason: "Urgent banking verification and document stamping.",
    appliedDate: "2026-06-30",
    status: "Approved",
    approver: "Vikram Malhotra",
    remarks: "Approved half day.",
    attachment: null,
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-06-30 04:00 PM", status: "completed" },
      { step: "Manager Approval", by: "Vikram Malhotra", date: "2026-07-01 09:10 AM", status: "completed" },
    ],
  },
  {
    id: "LV-2026-005",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Earned Leave",
    leaveCode: "EL",
    fromDate: "2026-06-12",
    toDate: "2026-06-14",
    days: 3,
    halfDay: false,
    reason: "Personal travel.",
    appliedDate: "2026-06-05",
    status: "Rejected",
    approver: "Vikram Malhotra",
    remarks: "Critical production release scheduled on June 13. Please reschedule.",
    attachment: null,
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-06-05 09:00 AM", status: "completed" },
      { step: "Manager Rejected", by: "Vikram Malhotra", date: "2026-06-06 11:30 AM", status: "rejected" },
    ],
  },
  {
    id: "LV-2026-006",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    department: "Engineering",
    leaveType: "Compensatory Off",
    leaveCode: "CO",
    fromDate: "2026-05-20",
    toDate: "2026-05-20",
    days: 1,
    halfDay: false,
    reason: "Comp-off for server maintenance on Sunday May 17.",
    appliedDate: "2026-05-18",
    status: "Cancelled",
    approver: "Vikram Malhotra",
    remarks: "Cancelled by employee prior to start date.",
    attachment: null,
    approvalTimeline: [
      { step: "Submitted", by: "Aarav Sharma", date: "2026-05-18 10:00 AM", status: "completed" },
      { step: "Cancelled", by: "Aarav Sharma", date: "2026-05-19 03:20 PM", status: "cancelled" },
    ],
  },
];

export const INITIAL_TEAM_LEAVES = [
  ...INITIAL_MY_LEAVES,
  {
    id: "LV-2026-007",
    employeeId: "EMP-1005",
    employeeName: "Neha Verma",
    department: "Engineering",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    leaveType: "Casual Leave",
    leaveCode: "CL",
    fromDate: "2026-09-22",
    toDate: "2026-09-23",
    days: 2,
    halfDay: false,
    reason: "Parent-teacher meetings and house relocation.",
    appliedDate: "2026-09-18",
    status: "Pending",
    approver: "Vikram Malhotra",
    remarks: "Pending manager decision",
    attachment: null,
  },
  {
    id: "LV-2026-008",
    employeeId: "EMP-1006",
    employeeName: "Rohan Kulkarni",
    department: "Engineering",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    leaveType: "Sick Leave",
    leaveCode: "SL",
    fromDate: "2026-09-21",
    toDate: "2026-09-21",
    days: 1,
    halfDay: false,
    reason: "Severe migraine and doctor appointment.",
    appliedDate: "2026-09-21",
    status: "Approved",
    approver: "Vikram Malhotra",
    remarks: "Approved by manager.",
    attachment: "dr_slip.jpg",
  },
  {
    id: "LV-2026-009",
    employeeId: "EMP-1007",
    employeeName: "Ananya Roy",
    department: "UI/UX Design",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    leaveType: "Earned Leave",
    leaveCode: "EL",
    fromDate: "2026-09-28",
    toDate: "2026-10-02",
    days: 5,
    halfDay: false,
    reason: "Attending international Design Systems Summit.",
    appliedDate: "2026-09-15",
    status: "Pending",
    approver: "Priya Nair",
    remarks: "Awaiting final HR approval",
    attachment: "ticket_conf.pdf",
  },
  {
    id: "LV-2026-010",
    employeeId: "EMP-1008",
    employeeName: "Devansh Mehta",
    department: "Sales & Marketing",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    leaveType: "Optional / Holiday",
    leaveCode: "OL",
    fromDate: "2026-09-25",
    toDate: "2026-09-25",
    days: 1,
    halfDay: false,
    reason: "Festive regional observation.",
    appliedDate: "2026-09-17",
    status: "Approved",
    approver: "Priya Nair",
    remarks: "Approved.",
    attachment: null,
  },
  {
    id: "LV-2026-011",
    employeeId: "EMP-1009",
    employeeName: "Sneha Patel",
    department: "Finance & Accounts",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    leaveType: "Casual Leave",
    leaveCode: "CL",
    fromDate: "2026-09-29",
    toDate: "2026-09-30",
    days: 2,
    halfDay: false,
    reason: "Home construction registry signing.",
    appliedDate: "2026-09-19",
    status: "Pending",
    approver: "Priya Nair",
    remarks: "Review in progress",
    attachment: null,
  },
];
