export const INITIAL_EMPLOYEES = [
  {
    id: "EMP-1001",
    name: "Deepika Sandhiya",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    department: "Executive Leadership",
    designation: "Chief Human Resources Officer (CHRO)",
    location: "Global HQ (Bangalore)",
    employmentType: "Full-Time",
    joiningDate: "2021-03-01",
    reportingManager: "Board of Directors",
    status: "Active",
    personal: {
      dob: "1988-06-14",
      gender: "Female",
      phone: "+91 98450 11223",
      email: "admin@infiniq.com",
      address: "Prestige Cyber Towers, Koramangala 4th Block, Bangalore - 560034",
    },
    emergency: {
      name: "Ramesh Sandhiya",
      relation: "Spouse",
      phone: "+91 98450 99887",
      address: "Prestige Cyber Towers, Koramangala 4th Block, Bangalore",
    },
    documents: [
      { name: "Executive_Appointment_Letter.pdf", type: "Offer/Contract", size: "1.4 MB", date: "2021-03-01" },
      { name: "National_ID_Aadhaar.pdf", type: "ID Proof", size: "850 KB", date: "2021-03-02" },
      { name: "MBA_Degree_Certificate.pdf", type: "Education", size: "2.1 MB", date: "2021-03-02" },
    ],
    leaveSummary: { total: 30, available: 16, used: 14, pending: 0 },
    attendanceSummary: { present: 21, absent: 0, late: 1, leave: 1 },
  },
  {
    id: "EMP-1002",
    name: "Vikram Malhotra",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    department: "Engineering",
    designation: "Engineering Director",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2021-08-15",
    reportingManager: "Deepika Sandhiya",
    status: "Active",
    personal: {
      dob: "1986-11-22",
      gender: "Male",
      phone: "+91 98110 33445",
      email: "vikram.m@infiniq.com",
      address: "Villa 42, Palm Meadows, Whitefield, Bangalore - 560066",
    },
    emergency: {
      name: "Sunita Malhotra",
      relation: "Spouse",
      phone: "+91 98110 66778",
      address: "Villa 42, Palm Meadows, Whitefield, Bangalore",
    },
    documents: [
      { name: "Employment_Agreement.pdf", type: "Contract", size: "1.2 MB", date: "2021-08-15" },
      { name: "Passport_Copy.pdf", type: "Identity", size: "1.8 MB", date: "2021-08-16" },
    ],
    leaveSummary: { total: 30, available: 18, used: 12, pending: 0 },
    attendanceSummary: { present: 22, absent: 0, late: 0, leave: 0 },
  },
  {
    id: "EMP-1003",
    name: "Priya Nair",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    department: "Human Resources",
    designation: "HR Lead & Operations Head",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2022-01-10",
    reportingManager: "Deepika Sandhiya",
    status: "Active",
    personal: {
      dob: "1991-04-19",
      gender: "Female",
      phone: "+91 97330 44556",
      email: "priya.nair@infiniq.com",
      address: "102 Silver Oak Apts, Indiranagar, Bangalore - 560038",
    },
    emergency: {
      name: "Suresh Nair",
      relation: "Father",
      phone: "+91 97330 11223",
      address: "Indiranagar, Bangalore",
    },
    documents: [
      { name: "Appointment_Offer.pdf", type: "Offer", size: "980 KB", date: "2022-01-10" },
      { name: "Background_Verification_Report.pdf", type: "Verification", size: "2.4 MB", date: "2022-01-15" },
    ],
    leaveSummary: { total: 30, available: 20, used: 10, pending: 0 },
    attendanceSummary: { present: 20, absent: 0, late: 2, leave: 0 },
  },
  {
    id: "EMP-1004",
    name: "Aarav Sharma",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    department: "Engineering",
    designation: "Senior Frontend Engineer",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2023-04-03",
    reportingManager: "Vikram Malhotra",
    status: "Active",
    personal: {
      dob: "1994-09-08",
      gender: "Male",
      phone: "+91 99001 88223",
      email: "aarav.sharma@infiniq.com",
      address: "Flat 4B, Green Glen Layout, Bellandur, Bangalore - 560103",
    },
    emergency: {
      name: "Kavita Sharma",
      relation: "Mother",
      phone: "+91 99001 33441",
      address: "Sector 14, Gurgaon, Haryana",
    },
    documents: [
      { name: "Senior_Engineer_Offer_Letter.pdf", type: "Offer", size: "1.1 MB", date: "2023-04-03" },
      { name: "BTech_Degree.pdf", type: "Education", size: "1.6 MB", date: "2023-04-04" },
      { name: "Relieving_Letter_Previous_Org.pdf", type: "Experience", size: "750 KB", date: "2023-04-05" },
    ],
    leaveSummary: { total: 30, available: 19, used: 9, pending: 2 },
    attendanceSummary: { present: 19, absent: 0, late: 1, leave: 2 },
  },
  {
    id: "EMP-1005",
    name: "Neha Verma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    department: "Engineering",
    designation: "Full Stack Engineer",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2023-06-12",
    reportingManager: "Vikram Malhotra",
    status: "Active",
    personal: {
      dob: "1996-03-25",
      gender: "Female",
      phone: "+91 98800 77112",
      email: "neha.verma@infiniq.com",
      address: "B-304, Brigade Metropolis, Mahadevapura, Bangalore - 560048",
    },
    emergency: {
      name: "Rajesh Verma",
      relation: "Spouse",
      phone: "+91 98800 11990",
      address: "Mahadevapura, Bangalore",
    },
    documents: [
      { name: "Offer_Letter.pdf", type: "Offer", size: "950 KB", date: "2023-06-12" },
      { name: "PAN_Card.pdf", type: "ID Proof", size: "620 KB", date: "2023-06-13" },
    ],
    leaveSummary: { total: 30, available: 22, used: 6, pending: 2 },
    attendanceSummary: { present: 21, absent: 0, late: 0, leave: 1 },
  },
  {
    id: "EMP-1006",
    name: "Rohan Kulkarni",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    department: "Engineering",
    designation: "DevOps & Cloud Engineer",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2023-09-01",
    reportingManager: "Vikram Malhotra",
    status: "On Leave",
    personal: {
      dob: "1993-12-11",
      gender: "Male",
      phone: "+91 97400 66221",
      email: "rohan.k@infiniq.com",
      address: "55, 7th Main, HSR Layout Sector 2, Bangalore - 560102",
    },
    emergency: {
      name: "Pooja Kulkarni",
      relation: "Sibling",
      phone: "+91 97400 44110",
      address: "HSR Layout, Bangalore",
    },
    documents: [
      { name: "Offer_DevOps.pdf", type: "Offer", size: "1.0 MB", date: "2023-09-01" },
    ],
    leaveSummary: { total: 30, available: 24, used: 5, pending: 1 },
    attendanceSummary: { present: 18, absent: 1, late: 2, leave: 1 },
  },
  {
    id: "EMP-1007",
    name: "Ananya Roy",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    department: "UI/UX Design",
    designation: "Lead Product Designer",
    location: "Mumbai Branch",
    employmentType: "Full-Time",
    joiningDate: "2022-11-15",
    reportingManager: "Priya Nair",
    status: "Active",
    personal: {
      dob: "1992-08-30",
      gender: "Female",
      phone: "+91 98200 44556",
      email: "ananya.roy@infiniq.com",
      address: "Sea View Heights, Bandra West, Mumbai - 400050",
    },
    emergency: {
      name: "Dr. Alok Roy",
      relation: "Father",
      phone: "+91 98200 88990",
      address: "Bandra West, Mumbai",
    },
    documents: [
      { name: "Offer_Letter_Lead_Designer.pdf", type: "Offer", size: "1.3 MB", date: "2022-11-15" },
    ],
    leaveSummary: { total: 30, available: 17, used: 8, pending: 5 },
    attendanceSummary: { present: 22, absent: 0, late: 0, leave: 0 },
  },
  {
    id: "EMP-1008",
    name: "Devansh Mehta",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    department: "Sales & Marketing",
    designation: "Enterprise Growth Specialist",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2024-01-08",
    reportingManager: "Priya Nair",
    status: "Probation",
    personal: {
      dob: "1997-02-14",
      gender: "Male",
      phone: "+91 96110 55223",
      email: "devansh.m@infiniq.com",
      address: "Sobha Dream Acres, Panathur, Bangalore - 560087",
    },
    emergency: {
      name: "Sanjay Mehta",
      relation: "Father",
      phone: "+91 96110 99881",
      address: "Ahmedabad, Gujarat",
    },
    documents: [
      { name: "Probation_Agreement.pdf", type: "Contract", size: "880 KB", date: "2024-01-08" },
    ],
    leaveSummary: { total: 15, available: 12, used: 2, pending: 1 },
    attendanceSummary: { present: 20, absent: 0, late: 2, leave: 0 },
  },
  {
    id: "EMP-1009",
    name: "Sneha Patel",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    department: "Finance & Accounts",
    designation: "Senior Financial Analyst",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2023-02-20",
    reportingManager: "Deepika Sandhiya",
    status: "Active",
    personal: {
      dob: "1994-05-18",
      gender: "Female",
      phone: "+91 99800 22334",
      email: "sneha.patel@infiniq.com",
      address: "Mantri Espana, Bellandur, Bangalore - 560103",
    },
    emergency: {
      name: "Kunal Patel",
      relation: "Spouse",
      phone: "+91 99800 66778",
      address: "Bellandur, Bangalore",
    },
    documents: [
      { name: "CA_Charter_Certificate.pdf", type: "Degree", size: "2.8 MB", date: "2023-02-20" },
    ],
    leaveSummary: { total: 30, available: 21, used: 7, pending: 2 },
    attendanceSummary: { present: 22, absent: 0, late: 0, leave: 0 },
  },
  {
    id: "EMP-1010",
    name: "Karthik Raja",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    department: "Operations",
    designation: "IT Systems Administrator",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2022-05-10",
    reportingManager: "Priya Nair",
    status: "Active",
    personal: {
      dob: "1993-10-05",
      gender: "Male",
      phone: "+91 98450 77889",
      email: "karthik.r@infiniq.com",
      address: "Jayanagar 4th T Block, Bangalore - 560041",
    },
    emergency: {
      name: "Meena Raja",
      relation: "Mother",
      phone: "+91 98450 44551",
      address: "Jayanagar, Bangalore",
    },
    documents: [
      { name: "ITIL_Cert.pdf", type: "Certification", size: "920 KB", date: "2022-05-10" },
    ],
    leaveSummary: { total: 30, available: 23, used: 7, pending: 0 },
    attendanceSummary: { present: 21, absent: 0, late: 1, leave: 0 },
  },
  {
    id: "EMP-1011",
    name: "Tanya Sen",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    department: "UI/UX Design",
    designation: "Associate Interaction Designer",
    location: "Remote",
    employmentType: "Contract",
    joiningDate: "2024-03-01",
    reportingManager: "Ananya Roy",
    status: "Active",
    personal: {
      dob: "1999-07-21",
      gender: "Female",
      phone: "+91 91100 44221",
      email: "tanya.sen@infiniq.com",
      address: "Salt Lake Sector V, Kolkata - 700091",
    },
    emergency: {
      name: "Sunil Sen",
      relation: "Father",
      phone: "+91 91100 88990",
      address: "Kolkata, West Bengal",
    },
    documents: [
      { name: "Contractor_Agreement.pdf", type: "Contract", size: "1.1 MB", date: "2024-03-01" },
    ],
    leaveSummary: { total: 15, available: 14, used: 1, pending: 0 },
    attendanceSummary: { present: 21, absent: 0, late: 0, leave: 1 },
  },
  {
    id: "EMP-1012",
    name: "Aditya Chopra",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    department: "Sales & Marketing",
    designation: "Content & Community Strategist",
    location: "Bangalore (HQ)",
    employmentType: "Full-Time",
    joiningDate: "2022-08-01",
    reportingManager: "Priya Nair",
    status: "Resigned",
    personal: {
      dob: "1995-01-15",
      gender: "Male",
      phone: "+91 99160 33441",
      email: "aditya.c@infiniq.com",
      address: "Domlur 2nd Stage, Bangalore - 560071",
    },
    emergency: {
      name: "Renu Chopra",
      relation: "Mother",
      phone: "+91 99160 11229",
      address: "Chandigarh",
    },
    documents: [
      { name: "Resignation_Acceptance.pdf", type: "HR Notice", size: "640 KB", date: "2026-08-20" },
    ],
    leaveSummary: { total: 30, available: 10, used: 20, pending: 0 },
    attendanceSummary: { present: 19, absent: 1, late: 1, leave: 1 },
  },
];
