export const INITIAL_ONBOARDING = [
  {
    id: "ONB-2026-101",
    employeeName: "Siddharth Menon",
    email: "siddharth.m@infiniq.com",
    joiningDate: "2026-10-01",
    department: "Engineering",
    designation: "Senior Backend Developer",
    currentStage: "IT/Asset Setup",
    stageIndex: 4,
    progress: 57,
    assignedHr: "Priya Nair",
    status: "In Progress",
    stages: [
      { id: 1, name: "Employee Information", status: "completed", date: "2026-09-12", notes: "Personal profile and Aadhaar verified." },
      { id: 2, name: "Documents", status: "completed", date: "2026-09-15", notes: "All degree certificates and previous relieving uploaded." },
      { id: 3, name: "Verification", status: "completed", date: "2026-09-18", notes: "Third-party background check cleared with green status." },
      { id: 4, name: "IT/Asset Setup", status: "in_progress", date: "2026-09-21", notes: "MacBook Pro M3 Max ordered; Slack & Google Workspace provisioned." },
      { id: 5, name: "HR Setup", status: "pending", date: null, notes: "Payroll structure and medical insurance enrollment." },
      { id: 6, name: "Final Approval", status: "pending", date: null, notes: "CHRO digital signature." },
      { id: 7, name: "Completed", status: "pending", date: null, notes: "Welcome kit dispatch & Day 1 orientation." },
    ],
  },
  {
    id: "ONB-2026-102",
    employeeName: "Ishita Roy",
    email: "ishita.r@infiniq.com",
    joiningDate: "2026-10-05",
    department: "UI/UX Design",
    designation: "Visual Design Specialist",
    currentStage: "Documents",
    stageIndex: 2,
    progress: 28,
    assignedHr: "Priya Nair",
    status: "In Progress",
    stages: [
      { id: 1, name: "Employee Information", status: "completed", date: "2026-09-16", notes: "Onboarding form submitted." },
      { id: 2, name: "Documents", status: "in_progress", date: "2026-09-20", notes: "Pending previous employer tax Form 16." },
      { id: 3, name: "Verification", status: "pending", date: null, notes: "Address check scheduled." },
      { id: 4, name: "IT/Asset Setup", status: "pending", date: null, notes: "Figma enterprise license assigned." },
      { id: 5, name: "HR Setup", status: "pending", date: null, notes: "" },
      { id: 6, name: "Final Approval", status: "pending", date: null, notes: "" },
      { id: 7, name: "Completed", status: "pending", date: null, notes: "" },
    ],
  },
  {
    id: "ONB-2026-103",
    employeeName: "Tanmay Bansal",
    email: "tanmay.b@infiniq.com",
    joiningDate: "2026-09-15",
    department: "Sales & Marketing",
    designation: "Mid-Market Account Executive",
    currentStage: "Completed",
    stageIndex: 7,
    progress: 100,
    assignedHr: "Priya Nair",
    status: "Completed",
    stages: [
      { id: 1, name: "Employee Information", status: "completed", date: "2026-08-25", notes: "Verified" },
      { id: 2, name: "Documents", status: "completed", date: "2026-08-28", notes: "All approved" },
      { id: 3, name: "Verification", status: "completed", date: "2026-09-02", notes: "Cleared" },
      { id: 4, name: "IT/Asset Setup", status: "completed", date: "2026-09-08", notes: "Hardware and Hubspot setup done" },
      { id: 5, name: "HR Setup", status: "completed", date: "2026-09-12", notes: "Benefits active" },
      { id: 6, name: "Final Approval", status: "completed", date: "2026-09-14", notes: "Approved by Deepika" },
      { id: 7, name: "Completed", status: "completed", date: "2026-09-15", notes: "Joined successfully" },
    ],
  },
  {
    id: "ONB-2026-104",
    employeeName: "Meera Krishnan",
    email: "meera.k@infiniq.com",
    joiningDate: "2026-10-15",
    department: "Finance & Accounts",
    designation: "Accounts Payable Associate",
    currentStage: "Employee Information",
    stageIndex: 1,
    progress: 14,
    assignedHr: "Priya Nair",
    status: "In Progress",
    stages: [
      { id: 1, name: "Employee Information", status: "in_progress", date: "2026-09-21", notes: "Offer accepted; filling personal questionnaire." },
      { id: 2, name: "Documents", status: "pending", date: null, notes: "" },
      { id: 3, name: "Verification", status: "pending", date: null, notes: "" },
      { id: 4, name: "IT/Asset Setup", status: "pending", date: null, notes: "" },
      { id: 5, name: "HR Setup", status: "pending", date: null, notes: "" },
      { id: 6, name: "Final Approval", status: "pending", date: null, notes: "" },
      { id: 7, name: "Completed", status: "pending", date: null, notes: "" },
    ],
  },
];

export const INITIAL_OFFBOARDING = [
  {
    id: "OFF-2026-201",
    employeeName: "Aditya Chopra",
    employeeId: "EMP-1012",
    department: "Sales & Marketing",
    manager: "Priya Nair",
    resignationDate: "2026-08-15",
    lastWorkingDate: "2026-09-30",
    currentStage: "Clearance",
    stageIndex: 5,
    status: "In Progress",
    progress: 62,
    clearances: {
      it: { status: "pending", remark: "MacBook and security key to be returned on last working day" },
      finance: { status: "approved", remark: "Travel reimbursements settled, no pending advances" },
      admin: { status: "approved", remark: "ID access badge and parking card deposited" },
      hr: { status: "pending", remark: "Exit interview scheduled for Sept 28" },
    },
    stages: [
      { id: 1, name: "Resignation", status: "completed", date: "2026-08-15" },
      { id: 2, name: "Manager Approval", status: "completed", date: "2026-08-18" },
      { id: 3, name: "HR Review", status: "completed", date: "2026-08-20" },
      { id: 4, name: "Asset Return", status: "in_progress", date: "2026-09-20" },
      { id: 5, name: "Clearance", status: "in_progress", date: "2026-09-21" },
      { id: 6, name: "Exit Interview", status: "pending", date: null },
      { id: 7, name: "Final Settlement", status: "pending", date: null },
      { id: 8, name: "Completed", status: "pending", date: null },
    ],
  },
  {
    id: "OFF-2026-202",
    employeeName: "Varun Kashyap",
    employeeId: "EMP-1015",
    department: "Engineering",
    manager: "Vikram Malhotra",
    resignationDate: "2026-07-20",
    lastWorkingDate: "2026-08-31",
    currentStage: "Completed",
    stageIndex: 8,
    status: "Completed",
    progress: 100,
    clearances: {
      it: { status: "approved", remark: "All repos and credentials revoked. Laptop formatted." },
      finance: { status: "approved", remark: "Full & Final payment credited on Sept 5." },
      admin: { status: "approved", remark: "Access cards surrendered." },
      hr: { status: "approved", remark: "Experience and relieving letter issued." },
    },
    stages: [
      { id: 1, name: "Resignation", status: "completed", date: "2026-07-20" },
      { id: 2, name: "Manager Approval", status: "completed", date: "2026-07-22" },
      { id: 3, name: "HR Review", status: "completed", date: "2026-07-24" },
      { id: 4, name: "Asset Return", status: "completed", date: "2026-08-28" },
      { id: 5, name: "Clearance", status: "completed", date: "2026-08-30" },
      { id: 6, name: "Exit Interview", status: "completed", date: "2026-08-31" },
      { id: 7, name: "Final Settlement", status: "completed", date: "2026-09-05" },
      { id: 8, name: "Completed", status: "completed", date: "2026-09-05" },
    ],
  },
];

export const INITIAL_HR_SERVICES = [
  {
    id: "HRS-2026-301",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    serviceType: "Employment Certificate",
    submittedDate: "2026-09-18",
    assignedTo: "Priya Nair",
    priority: "Medium",
    status: "In Progress",
    purpose: "Required for home loan mortgage application with HDFC Bank.",
    attachmentUrl: null,
    resolutionNotes: "Drafted letter with salary Annexure; awaiting CHRO seal.",
  },
  {
    id: "HRS-2026-302",
    employeeId: "EMP-1005",
    employeeName: "Neha Verma",
    serviceType: "Salary Certificate",
    submittedDate: "2026-09-19",
    assignedTo: "Priya Nair",
    priority: "High",
    status: "New",
    purpose: "Schengen tourist visa application requirements for November travel.",
    attachmentUrl: null,
    resolutionNotes: "",
  },
  {
    id: "HRS-2026-303",
    employeeId: "EMP-1006",
    employeeName: "Rohan Kulkarni",
    serviceType: "Address Update",
    submittedDate: "2026-09-10",
    assignedTo: "Priya Nair",
    priority: "Low",
    status: "Completed",
    purpose: "Updated residential address proof (Rental Agreement) attached for payroll records.",
    attachmentUrl: "rental_agreement_2026.pdf",
    resolutionNotes: "Address updated in HRMS core and PF portal database.",
  },
  {
    id: "HRS-2026-304",
    employeeId: "EMP-1007",
    employeeName: "Ananya Roy",
    serviceType: "ID Card Request",
    submittedDate: "2026-09-14",
    assignedTo: "Priya Nair",
    priority: "Medium",
    status: "Completed",
    purpose: "Lost previous RFID smartcard during intercity transit.",
    attachmentUrl: null,
    resolutionNotes: "New RFID card issued (Card ID: #RFID-9921).",
  },
  {
    id: "HRS-2026-305",
    employeeId: "EMP-1008",
    employeeName: "Devansh Mehta",
    serviceType: "Bank Details Update",
    submittedDate: "2026-09-20",
    assignedTo: "Priya Nair",
    priority: "High",
    status: "Pending",
    purpose: "Switched salary account from ICICI to Axis Bank; cancelled cheque provided.",
    attachmentUrl: "cancelled_cheque.pdf",
    resolutionNotes: "Waiting for verification call from finance team.",
  },
];

export const INITIAL_EMPLOYEE_REQUESTS = [
  {
    id: "REQ-2026-401",
    employeeId: "EMP-1004",
    employeeName: "Aarav Sharma",
    category: "Hardware & Equipment",
    subject: "Request for second 27-inch 4K external display for UI development",
    priority: "Medium",
    status: "In Progress",
    submittedDate: "2026-09-17",
    assignedTo: "Karthik Raja",
    description: "Multi-monitor setup needed for frontend visual regression debugging and Figma design side-by-side inspection.",
    thread: [
      { sender: "Aarav Sharma", role: "Employee", time: "2026-09-17 11:30 AM", message: "Hi IT team, requesting approval for a 4K display." },
      { sender: "Karthik Raja", role: "IT Admin", time: "2026-09-18 10:00 AM", message: "Request received. We have Dell U2723QE units arriving this Thursday." },
    ],
  },
  {
    id: "REQ-2026-402",
    employeeId: "EMP-1005",
    employeeName: "Neha Verma",
    category: "Policy Clarification",
    subject: "Inquiry on paternity / maternity benefits and health insurance top-up",
    priority: "Low",
    status: "Resolved",
    submittedDate: "2026-09-12",
    assignedTo: "Priya Nair",
    description: "Clarification regarding corporate mediclaim coverage for expectant parents.",
    thread: [
      { sender: "Neha Verma", role: "Employee", time: "2026-09-12 02:15 PM", message: "Can you provide the policy PDF for family floater coverage?" },
      { sender: "Priya Nair", role: "HR Admin", time: "2026-09-13 11:00 AM", message: "Shared insurance handbook via email. Sum insured is 7.5L." },
    ],
  },
  {
    id: "REQ-2026-403",
    employeeId: "EMP-1006",
    employeeName: "Rohan Kulkarni",
    category: "Shift / Attendance Adjustment",
    subject: "Shift schedule alignment for European client maintenance window",
    priority: "High",
    status: "Open",
    submittedDate: "2026-09-20",
    assignedTo: "Vikram Malhotra",
    description: "Requesting approval to work 01:00 PM to 10:00 PM IST for two weeks starting Oct 1st.",
    thread: [
      { sender: "Rohan Kulkarni", role: "Employee", time: "2026-09-20 04:30 PM", message: "Vikram, requested adjustment for client cloud cutover." },
    ],
  },
];
