export const INITIAL_CONFIG = {
  general: {
    companyName: "INFiniq Technologies Private Limited",
    companyLogo: "https://infiniq.com/logo.png",
    companyEmail: "people@infiniq.com",
    companyPhone: "+91 (80) 4122 8800",
    website: "https://infiniq.com",
    timeZone: "Asia/Kolkata (IST +05:30)",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12-hour",
    currency: "INR (₹)",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekStartDay: "Monday",
  },
  employee: {
    idPrefix: "INF-",
    startSequence: 1001,
    statuses: [
      { key: "active", label: "Active", enabled: true },
      { key: "on_leave", label: "On Leave", enabled: true },
      { key: "probation", label: "Probation", enabled: true },
      { key: "resigned", label: "Resigned", enabled: true },
      { key: "inactive", label: "Inactive", enabled: true },
    ],
    employmentTypes: ["Full-Time", "Part-Time", "Contract", "Intern"],
    departments: [
      "Executive Leadership",
      "Engineering",
      "UI/UX Design",
      "Human Resources",
      "Finance & Accounts",
      "Sales & Marketing",
      "Operations",
    ],
    designations: [
      "Chief Human Resources Officer (CHRO)",
      "Engineering Director",
      "HR Lead & Operations Head",
      "Senior Frontend Engineer",
      "Full Stack Engineer",
      "DevOps & Cloud Engineer",
      "Lead Product Designer",
      "Enterprise Growth Specialist",
      "Senior Financial Analyst",
      "IT Systems Administrator",
      "Associate Interaction Designer",
    ],
    locations: [
      "Global HQ (Bangalore)",
      "Mumbai Branch",
      "Hyderabad Technology Center",
      "Remote",
    ],
    reportingHierarchy: "Matrix (Department Head + Project Manager)",
    requiredFields: [
      { field: "Full Legal Name", required: true },
      { field: "Date of Birth", required: true },
      { field: "Official Email Address", required: true },
      { field: "Mobile Phone Number", required: true },
      { field: "Aadhaar / National ID", required: true },
      { field: "Emergency Contact", required: true },
      { field: "Bank Account Details", required: true },
      { field: "Permanent Address", required: true },
    ],
  },
  attendance: {
    workShiftStart: "09:30",
    workShiftEnd: "18:30",
    dailyWorkHours: 8,
    breakDurationMinutes: 60,
    shiftOptions: [
      "General Shift (09:30 - 18:30)",
      "Morning Shift (07:00 - 16:00)",
      "Evening Shift (13:00 - 22:00)",
      "Night Shift (21:00 - 06:00)",
      "Flexible Hours",
    ],
    webCheckIn: true,
    geoFencing: false,
    geoRadiusMeters: 200,
    ipRestriction: false,
    gracePeriodMinutes: 15,
    lateThresholdDeductions: 3,
    earlyDepartureThresholdMinutes: 30,
    earlyDeparturePenalty: true,
    overtimeEnabled: true,
    overtimeMinimumMinutes: 60,
    overtimeMultiplier: "1.5x",
    managerApprovalRequired: true,
  },
  leave: {
    types: [
      {
        id: "lt-cl",
        code: "CL",
        name: "Casual Leave",
        annualAllocation: 12,
        carryForward: false,
        maxCarryForward: 0,
        encashment: false,
        halfDay: true,
        attachmentRequired: false,
        approvalRequired: true,
        active: true,
      },
      {
        id: "lt-sl",
        code: "SL",
        name: "Sick Leave",
        annualAllocation: 10,
        carryForward: true,
        maxCarryForward: 5,
        encashment: false,
        halfDay: true,
        attachmentRequired: true,
        approvalRequired: true,
        active: true,
      },
      {
        id: "lt-el",
        code: "EL",
        name: "Earned Leave",
        annualAllocation: 18,
        carryForward: true,
        maxCarryForward: 30,
        encashment: true,
        halfDay: false,
        attachmentRequired: false,
        approvalRequired: true,
        active: true,
      },
      {
        id: "lt-co",
        code: "CO",
        name: "Compensatory Off",
        annualAllocation: 4,
        carryForward: false,
        maxCarryForward: 0,
        encashment: false,
        halfDay: true,
        attachmentRequired: false,
        approvalRequired: true,
        active: true,
      },
      {
        id: "lt-ol",
        code: "OL",
        name: "Optional / Holiday",
        annualAllocation: 3,
        carryForward: false,
        maxCarryForward: 0,
        encashment: false,
        halfDay: false,
        attachmentRequired: false,
        approvalRequired: true,
        active: true,
      },
    ],
    rules: {
      minimumNoticeDays: 3,
      maximumConsecutiveDays: 14,
      weekendSandwich: false,
      holidaySandwich: false,
      allowNegativeBalance: false,
      approvalLevels: "Two-Level (Reporting Manager -> HR)",
    },
  },
  workflows: [
    {
      id: "wf-leave",
      name: "Leave Approval Workflow",
      module: "Leave",
      active: true,
      steps: [
        { level: 1, approverRole: "Reporting Manager", required: true, slaHours: 24 },
        { level: 2, approverRole: "Department Manager", required: false, slaHours: 48 },
        { level: 3, approverRole: "HR Admin", required: true, slaHours: 24 },
      ],
    },
    {
      id: "wf-attendance",
      name: "Attendance Regularization Workflow",
      module: "Attendance",
      active: true,
      steps: [
        { level: 1, approverRole: "Reporting Manager", required: true, slaHours: 24 },
        { level: 2, approverRole: "HR Admin", required: true, slaHours: 24 },
      ],
    },
    {
      id: "wf-hr-services",
      name: "HR Service Request Workflow",
      module: "HR Services",
      active: true,
      steps: [
        { level: 1, approverRole: "HR Admin", required: true, slaHours: 48 },
        { level: 2, approverRole: "CHRO / Super Admin", required: false, slaHours: 72 },
      ],
    },
    {
      id: "wf-emp-requests",
      name: "Employee Grievance & Helpdesk Workflow",
      module: "Employee Requests",
      active: true,
      steps: [
        { level: 1, approverRole: "Department Lead", required: true, slaHours: 24 },
        { level: 2, approverRole: "Operations Head", required: true, slaHours: 48 },
      ],
    },
  ],
  permissions: {
    roles: ["Super Admin", "HR Admin", "HR Manager", "Manager", "Employee"],
    modules: [
      "Dashboard",
      "Team",
      "Attendance",
      "Leave",
      "Operations",
      "Configuration",
      "Reports",
      "Audit Logs",
    ],
    matrix: {
      "Super Admin": {
        Dashboard: { view: true, create: true, edit: true, delete: true, approve: true },
        Team: { view: true, create: true, edit: true, delete: true, approve: true },
        Attendance: { view: true, create: true, edit: true, delete: true, approve: true },
        Leave: { view: true, create: true, edit: true, delete: true, approve: true },
        Operations: { view: true, create: true, edit: true, delete: true, approve: true },
        Configuration: { view: true, create: true, edit: true, delete: true, approve: true },
        Reports: { view: true, create: true, edit: true, delete: true, approve: true },
        "Audit Logs": { view: true, create: true, edit: true, delete: true, approve: true },
      },
      "HR Admin": {
        Dashboard: { view: true, create: true, edit: true, delete: false, approve: true },
        Team: { view: true, create: true, edit: true, delete: false, approve: true },
        Attendance: { view: true, create: true, edit: true, delete: false, approve: true },
        Leave: { view: true, create: true, edit: true, delete: true, approve: true },
        Operations: { view: true, create: true, edit: true, delete: true, approve: true },
        Configuration: { view: true, create: true, edit: true, delete: false, approve: true },
        Reports: { view: true, create: true, edit: true, delete: false, approve: true },
        "Audit Logs": { view: true, create: false, edit: false, delete: false, approve: false },
      },
      "HR Manager": {
        Dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
        Team: { view: true, create: true, edit: true, delete: false, approve: true },
        Attendance: { view: true, create: true, edit: true, delete: false, approve: true },
        Leave: { view: true, create: true, edit: true, delete: false, approve: true },
        Operations: { view: true, create: true, edit: true, delete: false, approve: true },
        Configuration: { view: true, create: false, edit: false, delete: false, approve: false },
        Reports: { view: true, create: false, edit: false, delete: false, approve: false },
        "Audit Logs": { view: true, create: false, edit: false, delete: false, approve: false },
      },
      Manager: {
        Dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
        Team: { view: true, create: false, edit: false, delete: false, approve: true },
        Attendance: { view: true, create: true, edit: true, delete: false, approve: true },
        Leave: { view: true, create: true, edit: false, delete: false, approve: true },
        Operations: { view: true, create: false, edit: false, delete: false, approve: true },
        Configuration: { view: false, create: false, edit: false, delete: false, approve: false },
        Reports: { view: true, create: false, edit: false, delete: false, approve: false },
        "Audit Logs": { view: false, create: false, edit: false, delete: false, approve: false },
      },
      Employee: {
        Dashboard: { view: true, create: false, edit: false, delete: false, approve: false },
        Team: { view: true, create: false, edit: false, delete: false, approve: false },
        Attendance: { view: true, create: true, edit: false, delete: false, approve: false },
        Leave: { view: true, create: true, edit: false, delete: false, approve: false },
        Operations: { view: false, create: false, edit: false, delete: false, approve: false },
        Configuration: { view: false, create: false, edit: false, delete: false, approve: false },
        Reports: { view: false, create: false, edit: false, delete: false, approve: false },
        "Audit Logs": { view: false, create: false, edit: false, delete: false, approve: false },
      },
    },
  },
};
